
int absVal(int);
int test_absVal(int);
int allEvenBits();
int test_allEvenBits();
int bang(int);
int test_bang(int);
int bitAnd(int, int);
int test_bitAnd(int, int);
int bitCount(int);
int test_bitCount(int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int divpwr2(int, int);
int test_divpwr2(int, int);
unsigned float_abs(unsigned);
unsigned test_float_abs(unsigned);
unsigned float_neg(unsigned);
unsigned test_float_neg(unsigned);
unsigned float_twice(unsigned);
unsigned test_float_twice(unsigned);
int getByte(int, int);
int test_getByte(int, int);
int isLessOrEqual(int, int);
int test_isLessOrEqual(int, int);
int isNegative(int);
int test_isNegative(int);
int isNonNegative(int);
int test_isNonNegative(int);
int isPower2(int);
int test_isPower2(int);
int isTmax(int);
int test_isTmax(int);
int isZero(int);
int test_isZero(int);
int leastBitPos(int);
int test_leastBitPos(int);
int logicalShift(int, int);
int test_logicalShift(int, int);
int minusOne();
int test_minusOne();
int negate(int);
int test_negate(int);
int replaceByte(int, int, int);
int test_replaceByte(int, int, int);
int sign(int);
int test_sign(int);
int tmin();
int test_tmin();
int upperBits(int);
int test_upperBits(int);
